### ISSUE TITLE
Preferred Name Section

### ISSUE THREAD

**Issue by FMGstaff** [fraternity-management-group/gms#11]
Can we use the "First Name" section for this? Is it possible to link this?

**Comment by jdfergason** [comment]
Currently the Wufoo Automatic Import does not allow fields to be mapped directly to "First Name" or "Last Name". The only thing the software uses name for is to try and match records against existing donors. Marking as an enhancement to add "First Name" and "Last Name" as fields that can be mapped.

**Comment by jdfergason** [comment]
Added FirstName and LastName link fields. Released in version 3.0.1
