### ISSUE TITLE
Creating Automatic Charge to EDFO and HOUS accounts

### ISSUE THREAD

**Issue by FMGstaff** [fraternity-management-group/gms#16]
**Form name**
Donation Forms for full service clients

**Expected behavior**
Add ability to automatically create a charge for EDFO and HOUS payments.

**Additional context**
Jeremy, can we choose which client we do this for as in some cases this might of been a pledge and the charge is already there?
-Matt

**Comment by jdfergason** [comment]
Per conversation with Matt on 1/3/21 - closed
