### ISSUE TITLE
Social Media's

### ISSUE THREAD

**Issue by FMGstaff** [fraternity-management-group/gms#17]
**Form name**
CALPOLYSN Alumni Update INT (#2)
**Entry id**
What is the Wufoo entry id that caused the error? Note: this can be found on the wufoo view entries page, and is the number in the "id" column.
#2

**Expected behavior**
When an alumni adds that they are on specific social media platforms, we are seeing "Instagram" or "Facebook" being entered on the main page where the links to their profiles belong. They should be added to the group codes that are labeled "On Facebook" and the main page should only be used if we are given the direct link to their profile.  

**Additional context**
We have seen this with a few others forms as well.
See OUKS Alumni Update INT #2 as well.

**Comment by jdfergason** [comment]
This is not a bug in the software it's just in the way that it's setup. The link form is configured to use the categorical field "Which social media so you use? Please check all that apply. LinkedIn is very important for career networking and Facebook is the most used by alumni." for the sections facebook, twitter, so on and so forth.
<img width="849" alt="Screen Shot 2020-12-29 at 9 25 35 PM" src="https://user-images.githubusercontent.com/747109/103329971-9c7e6180-4a1c-11eb-99eb-f5f2a3a19329.png">
