### ISSUE TITLE
OSUKS Reports with Contradicting information

### ISSUE THREAD

**Issue by FMGstaff** [fraternity-management-group/gms#18]
**Report name**
Member Directory & Statistics/Graph

**Client Id**
OSUKS

**Index option**
Name order (for member directory report) 

**Run by**
Grad Date 

**Filter**
What filter did you use? Need the specific details of what the filter was. If a custom filter include all options that were selected.
On the member directory report -> Only thing that was selected was the "parent" code. 

**Expected behavior**
Expect member directory report and stats report to come back with the same number of profiles. With OSUKS, the stat report is telling us we have 158 parents in the database that are all set to inactive. A member directory report for all parents is returning with 147 profiles. We are not sure why this is occurring. 

**Additional context**

**Comment by jdfergason** [comment]
The reports are correct.

The member directory requires that an address, phone, or e-mail be present, there must be 11 members that don't meet this requirement which is why there is a discrepancy in the count. The stats/graph does not. If you run a name dump with the same Parent filter you also get 158, just like the stats/graph.

**Comment by FMGstaff** [comment]
Here are the names I was sent that had discrepancies with them. 
Delinda Draper

Darryl and Casey Kates

Roxanne and Sean Kharche

John and Tracy Schinharl

Valerie Schloss

David and Susan Skursha

Bojin and Yonka Slavov

Toni Urbanic 

-Eli

**Comment by jdfergason** [comment]
No discrepancies here, all the names listed don't have the required address.

Delinda Draper - No Address, Phone or E-mail
Darryl and Casey Kates - No Address, Phone or E-mail
Roxanne and Sean Kharche - No Address or Phone
John and Tracy Schinharl - No Address or Phone
Valerie Schloss - No Address
David and Susan Skursha - No Address 
Bojin and Yonka Slavov - No Address or Phone
Toni Urbanic - No Address or Phone
