### ISSUE TITLE
Address Did Not Update

### ISSUE THREAD

**Issue by FMGstaff** [fraternity-management-group/gms#23]
**Form name**
OSUKS Alumni Update

**Entry id**
#2 - Steven Schippel

**Expected behavior**
Expect address to automatically update via wufoo import system. 
**Additional context**
Home phone and email both automatically updated, address is the only thing that did not.

**Comment by jdfergason** [comment]
The entered address was invalid, it didn't have a state associated with it:

33850 Parkside Dr
Columbia Station
44028
United States

So validation system rejected.
